/* ==========================================================================
   CodeQuest — Embedded Question Bank (AI-authored)
   --------------------------------------------------------------------------
   Each question:
     { lang, diff, topic, question, code, options:[A..D], correct, explanation }
   - "code" is a snippet shown in a code box, or "" when not needed.
   - "options" must start with "A) ", "B) ", etc. One matches "correct".
   The game filters by language + difficulty (+ topics if chosen) and will
   broaden automatically if fewer than 10 match, so it never stalls.
   ========================================================================== */
window.QUESTION_BANK = [

/* ===================== PYTHON ===================== */

/* -- Beginner -- */
{lang:'Python',diff:'Beginner',topic:'Variables & Types',question:'What is the data type of the value 3.14 in Python?',code:'',options:['A) int','B) float','C) str','D) bool'],correct:'B',explanation:'Numbers written with a decimal point are floating-point values, so 3.14 is a float.'},
{lang:'Python',diff:'Beginner',topic:'Variables & Types',question:'What does the following code print?',code:'x = 5\ny = "5"\nprint(x == y)',options:['A) True','B) False','C) 5','D) Error'],correct:'B',explanation:'An int (5) is never equal to a str ("5"), so the comparison returns False.'},
{lang:'Python',diff:'Beginner',topic:'Conditionals',question:'Which keyword is used for an "otherwise" branch in Python?',code:'',options:['A) elseif','B) elif','C) else','D) otherwise'],correct:'C',explanation:'else handles the fallback branch; elif is used for additional conditions before it.'},
{lang:'Python',diff:'Beginner',topic:'Loops',question:'How many times does this loop run?',code:'for i in range(3):\n    print(i)',options:['A) 2 times','B) 3 times','C) 4 times','D) Infinite'],correct:'B',explanation:'range(3) yields 0, 1, 2 — three values — so the loop body runs 3 times.'},
{lang:'Python',diff:'Beginner',topic:'Lists & Tuples',question:'What is the result of this code?',code:'nums = [1, 2, 3]\nprint(nums[-1])',options:['A) 1','B) 2','C) 3','D) Error'],correct:'C',explanation:'Negative indices count from the end, so nums[-1] is the last element, 3.'},
{lang:'Python',diff:'Beginner',topic:'Functions',question:'What does a function return if it has no return statement?',code:'',options:['A) 0','B) None','C) Empty string','D) Error'],correct:'B',explanation:'A Python function with no explicit return implicitly returns None.'},

/* -- Intermediate -- */
{lang:'Python',diff:'Intermediate',topic:'Comprehensions',question:'What does this list comprehension produce?',code:'[x*x for x in range(4) if x % 2 == 0]',options:['A) [0, 4]','B) [0, 1, 4, 9]','C) [4, 16]','D) [0, 4, 16]'],correct:'A',explanation:'Only even x (0 and 2) pass the filter; squaring them gives 0 and 4.'},
{lang:'Python',diff:'Intermediate',topic:'Dictionaries',question:'Which method returns a default value instead of raising KeyError for a missing key?',code:'',options:['A) d.fetch(key)','B) d[key]','C) d.get(key, default)','D) d.find(key)'],correct:'C',explanation:'dict.get(key, default) returns default when the key is absent instead of raising KeyError.'},
{lang:'Python',diff:'Intermediate',topic:'Lambda & Map',question:'What is the output?',code:'nums = [1, 2, 3]\nprint(list(map(lambda x: x + 1, nums)))',options:['A) [1, 2, 3]','B) [2, 3, 4]','C) [1, 2, 3, 4]','D) Error'],correct:'B',explanation:'map applies the lambda to each element, adding 1, producing [2, 3, 4].'},
{lang:'Python',diff:'Intermediate',topic:'Error Handling',question:'Which block always runs whether or not an exception occurs?',code:'',options:['A) except','B) else','C) finally','D) raise'],correct:'C',explanation:'The finally block executes regardless of whether an exception was raised or handled.'},
{lang:'Python',diff:'Intermediate',topic:'Functions',question:'What does *args allow a function to accept?',code:'',options:['A) Keyword arguments only','B) A variable number of positional arguments','C) Exactly one argument','D) Default values'],correct:'B',explanation:'*args collects any number of extra positional arguments into a tuple.'},
{lang:'Python',diff:'Intermediate',topic:'Lists & Tuples',question:'What is the output of this slice?',code:'a = [0, 1, 2, 3, 4]\nprint(a[1:4])',options:['A) [1, 2, 3]','B) [1, 2, 3, 4]','C) [0, 1, 2, 3]','D) [2, 3, 4]'],correct:'A',explanation:'Slicing a[1:4] includes indices 1, 2, 3 but excludes 4, giving [1, 2, 3].'},

/* -- Advanced -- */
{lang:'Python',diff:'Advanced',topic:'OOP & Classes',question:'What is the purpose of the __init__ method?',code:'',options:['A) Destroy an object','B) Initialize a new instance','C) Compare two objects','D) Convert to string'],correct:'B',explanation:'__init__ is the constructor that initializes attributes when a new instance is created.'},
{lang:'Python',diff:'Advanced',topic:'Comprehensions',question:'What does this generator expression evaluate to?',code:'sum(x for x in range(5))',options:['A) 10','B) 15','C) 5','D) [0,1,2,3,4]'],correct:'A',explanation:'It sums 0+1+2+3+4 = 10; a generator expression streams values lazily into sum().'},
{lang:'Python',diff:'Advanced',topic:'Functions',question:'What will this closure print?',code:'def outer():\n    x = 10\n    def inner():\n        return x + 1\n    return inner\nprint(outer()())',options:['A) 10','B) 11','C) Error','D) None'],correct:'B',explanation:'inner closes over x from outer, so calling the returned function returns 10 + 1 = 11.'},
{lang:'Python',diff:'Advanced',topic:'OOP & Classes',question:'What does a decorator do in Python?',code:'',options:['A) Deletes a function','B) Wraps a function to extend its behavior','C) Renames a variable','D) Imports a module'],correct:'B',explanation:'A decorator is a callable that takes a function and returns a modified/wrapped function.'},
{lang:'Python',diff:'Advanced',topic:'Modules & Imports',question:'What does the value of __name__ equal when a file is run directly?',code:'',options:['A) The filename','B) "__main__"','C) "module"','D) None'],correct:'B',explanation:'When a script runs directly, Python sets __name__ to "__main__"; when imported, it is the module name.'},
{lang:'Python',diff:'Advanced',topic:'Error Handling',question:'What is the output?',code:'try:\n    print(1/0)\nexcept ZeroDivisionError:\n    print("caught")',options:['A) 0','B) caught','C) Error','D) inf'],correct:'B',explanation:'Dividing by zero raises ZeroDivisionError, which the except block catches and prints "caught".'},

/* ===================== JAVASCRIPT ===================== */

/* -- Beginner -- */
{lang:'JavaScript',diff:'Beginner',topic:'Variables & Scope',question:'Which keyword declares a variable that cannot be reassigned?',code:'',options:['A) var','B) let','C) const','D) static'],correct:'C',explanation:'const creates a binding that cannot be reassigned (though objects it points to can still mutate).'},
{lang:'JavaScript',diff:'Beginner',topic:'Data Types',question:'What does typeof return for this value?',code:'typeof "hello"',options:['A) "text"','B) "string"','C) "str"','D) "char"'],correct:'B',explanation:'String literals have the type "string", which typeof reports.'},
{lang:'JavaScript',diff:'Beginner',topic:'Data Types',question:'What is the result?',code:'console.log(2 + "2")',options:['A) 4','B) "22"','C) 22','D) NaN'],correct:'B',explanation:'When one operand is a string, + concatenates, so 2 + "2" becomes the string "22".'},
{lang:'JavaScript',diff:'Beginner',topic:'Arrays',question:'How do you add an element to the end of an array?',code:'',options:['A) arr.push(x)','B) arr.add(x)','C) arr.append(x)','D) arr.end(x)'],correct:'A',explanation:'Array.prototype.push() appends one or more elements to the end of the array.'},
{lang:'JavaScript',diff:'Beginner',topic:'Functions',question:'What is the output?',code:'function add(a, b) {\n  return a + b;\n}\nconsole.log(add(2, 3));',options:['A) 23','B) 5','C) undefined','D) Error'],correct:'B',explanation:'The function returns the numeric sum of 2 and 3, which is 5.'},
{lang:'JavaScript',diff:'Beginner',topic:'Variables & Scope',question:'What value does an unassigned declared variable hold?',code:'let x;\nconsole.log(x);',options:['A) null','B) 0','C) undefined','D) ""'],correct:'C',explanation:'A declared but unassigned variable holds the value undefined.'},

/* -- Intermediate -- */
{lang:'JavaScript',diff:'Intermediate',topic:'Arrays',question:'What does this map call return?',code:'[1, 2, 3].map(n => n * 2)',options:['A) [1, 2, 3]','B) [2, 4, 6]','C) 12','D) [1, 4, 9]'],correct:'B',explanation:'map returns a new array with each element transformed by the callback, doubling each value.'},
{lang:'JavaScript',diff:'Intermediate',topic:'ES6+ Features',question:'What does destructuring assign here?',code:'const [a, b] = [10, 20];\nconsole.log(b);',options:['A) 10','B) 20','C) [10, 20]','D) undefined'],correct:'B',explanation:'Array destructuring assigns by position, so a=10 and b=20.'},
{lang:'JavaScript',diff:'Intermediate',topic:'Functions',question:'What is the output?',code:'const greet = name => `Hi ${name}`;\nconsole.log(greet("Sam"));',options:['A) Hi name','B) Hi Sam','C) Hi ${name}','D) Error'],correct:'B',explanation:'Template literals interpolate ${name}, and the arrow function returns "Hi Sam".'},
{lang:'JavaScript',diff:'Intermediate',topic:'Data Types',question:'What does === check that == does not?',code:'',options:['A) Only value','B) Both value and type (no coercion)','C) Reference only','D) Nothing different'],correct:'B',explanation:'=== is strict equality: it compares value and type without type coercion, unlike ==.'},
{lang:'JavaScript',diff:'Intermediate',topic:'Arrays',question:'What does filter return?',code:'[1, 2, 3, 4].filter(n => n % 2 === 0)',options:['A) [1, 3]','B) [2, 4]','C) true','D) [1, 2, 3, 4]'],correct:'B',explanation:'filter keeps only elements for which the callback is true — here the even numbers 2 and 4.'},
{lang:'JavaScript',diff:'Intermediate',topic:'Objects',question:'How do you access the property "age" on object person?',code:'',options:['A) person->age','B) person.age','C) person::age','D) person(age)'],correct:'B',explanation:'Dot notation person.age (or bracket notation person["age"]) accesses object properties.'},

/* -- Advanced -- */
{lang:'JavaScript',diff:'Advanced',topic:'Closures',question:'What does this counter log on the second call?',code:'function counter() {\n  let c = 0;\n  return () => ++c;\n}\nconst next = counter();\nnext();\nconsole.log(next());',options:['A) 0','B) 1','C) 2','D) undefined'],correct:'C',explanation:'The closure remembers c between calls; first call makes it 1, second logs 2.'},
{lang:'JavaScript',diff:'Advanced',topic:'Promises & Async',question:'What does an async function always return?',code:'',options:['A) undefined','B) A Promise','C) A callback','D) The raw value'],correct:'B',explanation:'An async function always returns a Promise that resolves with its return value.'},
{lang:'JavaScript',diff:'Advanced',topic:'Promises & Async',question:'What prints first?',code:'console.log("A");\nsetTimeout(() => console.log("B"), 0);\nconsole.log("C");',options:['A) A B C','B) A C B','C) B A C','D) C B A'],correct:'B',explanation:'setTimeout defers its callback to the task queue, so synchronous A and C log before B.'},
{lang:'JavaScript',diff:'Advanced',topic:'ES6+ Features',question:'What does the spread operator do here?',code:'const a = [1, 2];\nconst b = [...a, 3];\nconsole.log(b);',options:['A) [[1,2],3]','B) [1, 2, 3]','C) [1, 2]','D) Error'],correct:'B',explanation:'The spread ...a expands the array elements into b, producing [1, 2, 3].'},
{lang:'JavaScript',diff:'Advanced',topic:'Closures',question:'What is logged?',code:'for (let i = 0; i < 3; i++) {\n  setTimeout(() => console.log(i), 0);\n}',options:['A) 0 1 2','B) 3 3 3','C) 0 0 0','D) 1 2 3'],correct:'A',explanation:'let creates a new binding of i per iteration, so each callback captures 0, 1, 2 respectively.'},
{lang:'JavaScript',diff:'Advanced',topic:'OOP & Classes',question:'What keyword calls the parent class constructor?',code:'',options:['A) parent()','B) base()','C) super()','D) this()'],correct:'C',explanation:'super() invokes the parent class constructor from within a subclass constructor.'},

/* ===================== JAVA ===================== */

/* -- Beginner -- */
{lang:'Java',diff:'Beginner',topic:'Variables & Types',question:'Which type stores a single character in Java?',code:'',options:['A) String','B) char','C) str','D) character'],correct:'B',explanation:'char holds a single 16-bit Unicode character, written with single quotes like \'A\'.'},
{lang:'Java',diff:'Beginner',topic:'Variables & Types',question:'What is the default value of an int field?',code:'',options:['A) null','B) 0','C) undefined','D) 1'],correct:'B',explanation:'Numeric instance fields default to 0 (int), 0.0 (double), etc., when not initialized.'},
{lang:'Java',diff:'Beginner',topic:'Methods',question:'Which keyword means a method belongs to the class, not an instance?',code:'',options:['A) final','B) static','C) public','D) void'],correct:'B',explanation:'static members belong to the class itself and can be called without creating an instance.'},
{lang:'Java',diff:'Beginner',topic:'Control Flow',question:'What does this print?',code:'int x = 4;\nif (x > 3) System.out.println("big");\nelse System.out.println("small");',options:['A) big','B) small','C) 4','D) Error'],correct:'A',explanation:'Since 4 > 3 is true, the if branch runs and prints "big".'},
{lang:'Java',diff:'Beginner',topic:'Strings',question:'How do you get the length of a String s?',code:'',options:['A) s.size()','B) s.length()','C) s.length','D) len(s)'],correct:'B',explanation:'String exposes length() as a method (arrays use the length field, without parentheses).'},
{lang:'Java',diff:'Beginner',topic:'Arrays',question:'What is the index of the first element of an array?',code:'',options:['A) 1','B) 0','C) -1','D) Depends'],correct:'B',explanation:'Java arrays are zero-indexed, so the first element is at index 0.'},

/* -- Intermediate -- */
{lang:'Java',diff:'Intermediate',topic:'OOP & Classes',question:'What does the "extends" keyword indicate?',code:'',options:['A) Implementing an interface','B) Class inheritance','C) Importing a package','D) Declaring a constant'],correct:'B',explanation:'extends declares that a class inherits from a superclass; interfaces use implements.'},
{lang:'Java',diff:'Intermediate',topic:'Collections',question:'Which collection does NOT allow duplicate elements?',code:'',options:['A) ArrayList','B) LinkedList','C) HashSet','D) Vector'],correct:'C',explanation:'A Set (e.g. HashSet) stores only unique elements and rejects duplicates.'},
{lang:'Java',diff:'Intermediate',topic:'Exceptions',question:'Which block is used to handle a thrown exception?',code:'',options:['A) try','B) catch','C) throw','D) finally'],correct:'B',explanation:'The catch block receives and handles exceptions thrown within the associated try block.'},
{lang:'Java',diff:'Intermediate',topic:'Strings',question:'Why is String immutable in Java?',code:'',options:['A) It can be changed freely','B) Its value cannot change after creation','C) It is always null','D) It has no methods'],correct:'B',explanation:'String objects are immutable; methods like concat return new strings rather than modifying the original.'},
{lang:'Java',diff:'Intermediate',topic:'Methods',question:'What is method overloading?',code:'',options:['A) Same name, different parameter lists','B) Same name and parameters in a subclass','C) Renaming a method','D) Deleting a method'],correct:'A',explanation:'Overloading defines multiple methods with the same name but different parameter signatures.'},
{lang:'Java',diff:'Intermediate',topic:'Control Flow',question:'What is missing to stop fall-through in a switch case?',code:'switch (x) {\n  case 1: doA();\n  case 2: doB();\n}',options:['A) return','B) break','C) continue','D) exit'],correct:'B',explanation:'Without break, execution falls through to subsequent cases; break ends the case.'},

/* -- Advanced -- */
{lang:'Java',diff:'Advanced',topic:'Generics',question:'What do generics like List<String> provide?',code:'',options:['A) Faster runtime','B) Compile-time type safety','C) Smaller memory','D) Automatic threading'],correct:'B',explanation:'Generics enforce type safety at compile time, avoiding unchecked casts and ClassCastExceptions.'},
{lang:'Java',diff:'Advanced',topic:'Interfaces',question:'Since Java 8, what can interfaces contain with a body?',code:'',options:['A) Only abstract methods','B) default methods','C) Constructors','D) Instance fields'],correct:'B',explanation:'Java 8 added default (and static) methods, letting interfaces provide method implementations.'},
{lang:'Java',diff:'Advanced',topic:'Lambdas',question:'What does this lambda represent?',code:'Runnable r = () -> System.out.println("run");',options:['A) A new thread','B) An implementation of run()','C) A syntax error','D) A static method'],correct:'B',explanation:'The lambda provides the body of Runnable\'s single abstract method run().'},
{lang:'Java',diff:'Advanced',topic:'OOP & Classes',question:'What does the "final" keyword on a class mean?',code:'',options:['A) It cannot be instantiated','B) It cannot be subclassed','C) It has no methods','D) It is abstract'],correct:'B',explanation:'A final class cannot be extended/subclassed (e.g. String is final).'},
{lang:'Java',diff:'Advanced',topic:'Collections',question:'What is the average time complexity of HashMap.get()?',code:'',options:['A) O(1)','B) O(n)','C) O(log n)','D) O(n^2)'],correct:'A',explanation:'A well-distributed HashMap offers average O(1) lookups thanks to hashing.'},
{lang:'Java',diff:'Advanced',topic:'Exceptions',question:'What is the difference between checked and unchecked exceptions?',code:'',options:['A) Checked must be declared or caught','B) Unchecked must always be caught','C) They are identical','D) Checked extend RuntimeException'],correct:'A',explanation:'Checked exceptions must be declared with throws or caught; unchecked (RuntimeException) need not be.'},

/* ===================== C++ ===================== */

/* -- Beginner -- */
{lang:'C++',diff:'Beginner',topic:'Variables & Types',question:'Which header is needed for std::cout?',code:'',options:['A) <stdio.h>','B) <iostream>','C) <string>','D) <vector>'],correct:'B',explanation:'std::cout and std::cin are declared in the <iostream> header.'},
{lang:'C++',diff:'Beginner',topic:'Control Flow',question:'What does this print?',code:'int x = 2;\nif (x == 2) std::cout << "yes";\nelse std::cout << "no";',options:['A) yes','B) no','C) 2','D) Error'],correct:'A',explanation:'x == 2 is true, so the if branch runs and prints "yes".'},
{lang:'C++',diff:'Beginner',topic:'Variables & Types',question:'Which operator outputs to the console with cout?',code:'',options:['A) >>','B) <<','C) ->','D) ::'],correct:'B',explanation:'The insertion operator << sends data to output streams like std::cout.'},
{lang:'C++',diff:'Beginner',topic:'Functions',question:'What return type means a function returns no value?',code:'',options:['A) null','B) void','C) int','D) empty'],correct:'B',explanation:'void indicates the function does not return a value.'},
{lang:'C++',diff:'Beginner',topic:'Variables & Types',question:'How do you declare an integer constant?',code:'',options:['A) const int x = 5;','B) int const = 5;','C) constant x = 5;','D) final int x = 5;'],correct:'A',explanation:'const int x = 5; declares a read-only integer that cannot be reassigned.'},
{lang:'C++',diff:'Beginner',topic:'Control Flow',question:'How many times does this loop run?',code:'for (int i = 0; i < 5; i++) {}',options:['A) 4','B) 5','C) 6','D) Infinite'],correct:'B',explanation:'i goes 0,1,2,3,4 — five iterations — before i < 5 becomes false.'},

/* -- Intermediate -- */
{lang:'C++',diff:'Intermediate',topic:'Pointers',question:'What does the * operator do when applied to a pointer p?',code:'',options:['A) Takes the address','B) Dereferences (gets the value)','C) Multiplies','D) Deletes it'],correct:'B',explanation:'Unary * dereferences a pointer, yielding the value it points to; & takes an address.'},
{lang:'C++',diff:'Intermediate',topic:'References',question:'What is a key property of a C++ reference?',code:'',options:['A) It can be null','B) It must be initialized and cannot be reseated','C) It uses pointer arithmetic','D) It needs delete'],correct:'B',explanation:'A reference must be bound at initialization and always refers to that same object thereafter.'},
{lang:'C++',diff:'Intermediate',topic:'STL Containers',question:'Which STL container provides dynamic, contiguous storage?',code:'',options:['A) std::list','B) std::vector','C) std::map','D) std::set'],correct:'B',explanation:'std::vector stores elements contiguously and resizes dynamically, like a growable array.'},
{lang:'C++',diff:'Intermediate',topic:'Functions',question:'What does passing by reference (int&) avoid?',code:'',options:['A) Compilation','B) Copying the argument','C) Returning a value','D) Using memory'],correct:'B',explanation:'Pass-by-reference avoids copying the argument and lets the function modify the caller\'s variable.'},
{lang:'C++',diff:'Intermediate',topic:'OOP & Classes',question:'By default, members of a C++ class are:',code:'',options:['A) public','B) private','C) protected','D) static'],correct:'B',explanation:'Class members default to private; struct members default to public.'},
{lang:'C++',diff:'Intermediate',topic:'STL Containers',question:'What does std::map store?',code:'',options:['A) Only keys','B) Sorted key-value pairs','C) A flat array','D) Unordered values'],correct:'B',explanation:'std::map keeps key-value pairs sorted by key (typically via a balanced tree).'},

/* -- Advanced -- */
{lang:'C++',diff:'Advanced',topic:'Memory Management',question:'What is the modern C++ way to manage a dynamically allocated object safely?',code:'',options:['A) raw new/delete','B) std::unique_ptr','C) malloc/free','D) goto'],correct:'B',explanation:'Smart pointers like std::unique_ptr provide RAII-based automatic cleanup, avoiding leaks.'},
{lang:'C++',diff:'Advanced',topic:'Templates',question:'What do templates enable?',code:'',options:['A) Runtime reflection','B) Generic code over multiple types','C) Garbage collection','D) Dynamic typing'],correct:'B',explanation:'Templates let you write type-generic functions and classes instantiated for each type at compile time.'},
{lang:'C++',diff:'Advanced',topic:'OOP & Classes',question:'What keyword makes a function able to be overridden polymorphically?',code:'',options:['A) static','B) virtual','C) inline','D) friend'],correct:'B',explanation:'A virtual function enables runtime polymorphism via dynamic dispatch through a base pointer/reference.'},
{lang:'C++',diff:'Advanced',topic:'Memory Management',question:'What problem does a dangling pointer represent?',code:'',options:['A) Pointer to freed/invalid memory','B) Pointer that is null','C) Pointer to a constant','D) Pointer to the stack'],correct:'A',explanation:'A dangling pointer references memory that has been freed or gone out of scope — using it is undefined behavior.'},
{lang:'C++',diff:'Advanced',topic:'OOP & Classes',question:'Why should a base class with virtual functions have a virtual destructor?',code:'',options:['A) For faster code','B) To ensure correct cleanup via base pointers','C) It is required by syntax','D) To prevent inheritance'],correct:'B',explanation:'A virtual destructor ensures the derived destructor runs when deleting through a base pointer, preventing leaks.'},
{lang:'C++',diff:'Advanced',topic:'STL Containers',question:'What does std::move primarily enable?',code:'',options:['A) Copying objects','B) Transferring resources via move semantics','C) Deleting objects','D) Sorting containers'],correct:'B',explanation:'std::move casts to an rvalue reference, allowing efficient transfer of resources instead of copying.'},

/* ===================== HTML/CSS ===================== */

/* -- Beginner -- */
{lang:'HTML/CSS',diff:'Beginner',topic:'HTML Structure',question:'Which tag creates the largest heading?',code:'',options:['A) <h6>','B) <head>','C) <h1>','D) <header>'],correct:'C',explanation:'<h1> is the top-level, largest heading; headings go down to <h6>.'},
{lang:'HTML/CSS',diff:'Beginner',topic:'HTML Structure',question:'Which attribute specifies an image source?',code:'<img ___="cat.png">',options:['A) href','B) src','C) link','D) source'],correct:'B',explanation:'The src attribute points to the image file the <img> element loads.'},
{lang:'HTML/CSS',diff:'Beginner',topic:'CSS Selectors',question:'Which selector targets an element with id="main"?',code:'',options:['A) .main','B) #main','C) main','D) *main'],correct:'B',explanation:'The # selector targets IDs; . targets classes.'},
{lang:'HTML/CSS',diff:'Beginner',topic:'HTML Structure',question:'Which tag creates a hyperlink?',code:'',options:['A) <link>','B) <a>','C) <href>','D) <nav>'],correct:'B',explanation:'The <a> (anchor) element with an href attribute creates a clickable hyperlink.'},
{lang:'HTML/CSS',diff:'Beginner',topic:'CSS Selectors',question:'How do you make text red in CSS?',code:'',options:['A) text-color: red;','B) color: red;','C) font-color: red;','D) fgcolor: red;'],correct:'B',explanation:'The color property sets the text (foreground) color of an element.'},
{lang:'HTML/CSS',diff:'Beginner',topic:'CSS Selectors',question:'Which selector targets elements with class="btn"?',code:'',options:['A) #btn','B) .btn','C) btn','D) :btn'],correct:'B',explanation:'A leading dot (.btn) selects elements by their class name.'},

/* -- Intermediate -- */
{lang:'HTML/CSS',diff:'Intermediate',topic:'Box Model',question:'Which box-model area is OUTSIDE the border?',code:'',options:['A) padding','B) content','C) margin','D) width'],correct:'C',explanation:'From inside out: content, padding, border, then margin — so margin is outside the border.'},
{lang:'HTML/CSS',diff:'Intermediate',topic:'Flexbox',question:'Which property aligns flex items along the main axis?',code:'',options:['A) align-items','B) justify-content','C) flex-wrap','D) order'],correct:'B',explanation:'justify-content distributes items along the main axis; align-items works on the cross axis.'},
{lang:'HTML/CSS',diff:'Intermediate',topic:'Box Model',question:'What does box-sizing: border-box do?',code:'',options:['A) Adds padding to width','B) Includes padding and border within the set width','C) Removes the border','D) Doubles the width'],correct:'B',explanation:'With border-box, the element\'s width includes padding and border, so the box does not grow beyond it.'},
{lang:'HTML/CSS',diff:'Intermediate',topic:'Pseudo-classes',question:'Which pseudo-class styles a link when hovered?',code:'',options:['A) :active','B) :hover','C) :focus','D) :visited'],correct:'B',explanation:':hover applies styles while the pointer is over the element.'},
{lang:'HTML/CSS',diff:'Intermediate',topic:'Positioning',question:'Which position value removes an element from normal flow and positions it relative to the nearest positioned ancestor?',code:'',options:['A) static','B) relative','C) absolute','D) sticky'],correct:'C',explanation:'position: absolute removes the element from flow and positions it relative to the nearest non-static ancestor.'},
{lang:'HTML/CSS',diff:'Intermediate',topic:'Semantic Tags',question:'Which tag best marks the main navigation links?',code:'',options:['A) <div>','B) <nav>','C) <section>','D) <aside>'],correct:'B',explanation:'<nav> is the semantic element for major navigation blocks of links.'},

/* -- Advanced -- */
{lang:'HTML/CSS',diff:'Advanced',topic:'Grid Layout',question:'Which property defines the columns of a CSS grid?',code:'',options:['A) grid-rows','B) grid-template-columns','C) flex-direction','D) column-count'],correct:'B',explanation:'grid-template-columns defines the number and sizes of columns in a grid container.'},
{lang:'HTML/CSS',diff:'Advanced',topic:'CSS Variables',question:'How do you read a custom property --gap in CSS?',code:'',options:['A) var(--gap)','B) $gap','C) get(--gap)','D) --gap()'],correct:'A',explanation:'Custom properties are accessed with the var() function, e.g. gap: var(--gap).'},
{lang:'HTML/CSS',diff:'Advanced',topic:'Responsive Design',question:'Which at-rule applies styles based on viewport width?',code:'',options:['A) @import','B) @media','C) @keyframes','D) @font-face'],correct:'B',explanation:'@media queries apply CSS conditionally based on features like width, enabling responsive design.'},
{lang:'HTML/CSS',diff:'Advanced',topic:'Animations',question:'Which rule defines the steps of a CSS animation?',code:'',options:['A) @transition','B) @keyframes','C) @animate','D) @motion'],correct:'B',explanation:'@keyframes defines the intermediate states; the animation property ties them to an element.'},
{lang:'HTML/CSS',diff:'Advanced',topic:'CSS Selectors',question:'What does the selector "div > p" match?',code:'',options:['A) Any p inside a div','B) Only p that are direct children of a div','C) p after a div','D) div inside a p'],correct:'B',explanation:'The > combinator selects only direct children, so it matches p elements that are immediate children of a div.'},
{lang:'HTML/CSS',diff:'Advanced',topic:'Flexbox',question:'What does flex: 1 on a flex item do?',code:'',options:['A) Fixes its width','B) Lets it grow to fill available space','C) Hides it','D) Sets order to 1'],correct:'B',explanation:'flex: 1 sets flex-grow to 1, so the item expands to share leftover space equally.'},

/* ===================== SQL ===================== */

/* -- Beginner -- */
{lang:'SQL',diff:'Beginner',topic:'SELECT Basics',question:'Which statement retrieves all columns from a table named users?',code:'',options:['A) GET * FROM users;','B) SELECT * FROM users;','C) SELECT ALL users;','D) FETCH users;'],correct:'B',explanation:'SELECT * FROM users; returns every column for all rows in the users table.'},
{lang:'SQL',diff:'Beginner',topic:'WHERE & Filters',question:'Which clause filters rows by a condition?',code:'',options:['A) FILTER','B) HAVING','C) WHERE','D) IF'],correct:'C',explanation:'WHERE restricts which rows are returned based on a condition.'},
{lang:'SQL',diff:'Beginner',topic:'SELECT Basics',question:'How do you limit results to 5 rows (standard / MySQL)?',code:'',options:['A) LIMIT 5','B) TOP 5 only','C) MAX 5','D) ROWS 5'],correct:'A',explanation:'LIMIT 5 returns at most 5 rows in MySQL/PostgreSQL/SQLite (SQL Server uses TOP).'},
{lang:'SQL',diff:'Beginner',topic:'SELECT Basics',question:'Which keyword sorts query results?',code:'',options:['A) SORT BY','B) ORDER BY','C) GROUP BY','D) ARRANGE'],correct:'B',explanation:'ORDER BY sorts the result set, ascending by default or descending with DESC.'},
{lang:'SQL',diff:'Beginner',topic:'WHERE & Filters',question:'Which operator matches a pattern in text?',code:'',options:['A) MATCH','B) LIKE','C) REGEX','D) CONTAINS'],correct:'B',explanation:'LIKE matches text patterns using wildcards % (any sequence) and _ (single character).'},
{lang:'SQL',diff:'Beginner',topic:'SELECT Basics',question:'Which keyword removes duplicate rows from results?',code:'',options:['A) UNIQUE','B) DISTINCT','C) ONLY','D) SINGLE'],correct:'B',explanation:'SELECT DISTINCT returns only unique combinations of the selected columns.'},

/* -- Intermediate -- */
{lang:'SQL',diff:'Intermediate',topic:'Aggregations',question:'Which function counts the number of rows?',code:'',options:['A) SUM()','B) COUNT()','C) TOTAL()','D) NUM()'],correct:'B',explanation:'COUNT() returns the number of rows (or non-null values of a column).'},
{lang:'SQL',diff:'Intermediate',topic:'GROUP BY',question:'Which clause filters groups after aggregation?',code:'',options:['A) WHERE','B) HAVING','C) FILTER','D) ON'],correct:'B',explanation:'HAVING filters grouped results (it can reference aggregates), whereas WHERE filters rows before grouping.'},
{lang:'SQL',diff:'Intermediate',topic:'JOINs',question:'Which JOIN returns only rows with matches in both tables?',code:'',options:['A) LEFT JOIN','B) INNER JOIN','C) FULL JOIN','D) CROSS JOIN'],correct:'B',explanation:'INNER JOIN returns rows only where the join condition matches in both tables.'},
{lang:'SQL',diff:'Intermediate',topic:'Aggregations',question:'What does AVG(price) compute?',code:'',options:['A) The largest price','B) The average price','C) The row count','D) The total price'],correct:'B',explanation:'AVG() returns the mean of the values in the specified column.'},
{lang:'SQL',diff:'Intermediate',topic:'INSERT & UPDATE',question:'Which statement changes existing rows?',code:'',options:['A) INSERT','B) UPDATE','C) ALTER','D) MODIFY'],correct:'B',explanation:'UPDATE ... SET ... WHERE ... modifies values in existing rows.'},
{lang:'SQL',diff:'Intermediate',topic:'GROUP BY',question:'What does GROUP BY do?',code:'SELECT dept, COUNT(*)\nFROM staff\nGROUP BY dept;',options:['A) Sorts by dept','B) Aggregates rows per dept','C) Deletes departments','D) Joins tables'],correct:'B',explanation:'GROUP BY collapses rows sharing the same dept into groups so aggregates are computed per department.'},

/* -- Advanced -- */
{lang:'SQL',diff:'Advanced',topic:'Subqueries',question:'What is a subquery?',code:'',options:['A) A query inside another query','B) A backup of a table','C) A stored procedure','D) A type of index'],correct:'A',explanation:'A subquery is a query nested within another statement, often in WHERE, FROM, or SELECT.'},
{lang:'SQL',diff:'Advanced',topic:'Indexes',question:'What is the main purpose of an index?',code:'',options:['A) Store backups','B) Speed up data retrieval','C) Enforce data types','D) Format output'],correct:'B',explanation:'Indexes speed up lookups and filtering at the cost of extra storage and slower writes.'},
{lang:'SQL',diff:'Advanced',topic:'Transactions',question:'Which command permanently saves changes in a transaction?',code:'',options:['A) SAVE','B) COMMIT','C) ROLLBACK','D) FLUSH'],correct:'B',explanation:'COMMIT makes all changes in the current transaction permanent; ROLLBACK undoes them.'},
{lang:'SQL',diff:'Advanced',topic:'JOINs',question:'What does a LEFT JOIN return?',code:'',options:['A) Only matching rows','B) All left rows plus matches (NULLs if none)','C) All right rows','D) Only non-matching rows'],correct:'B',explanation:'LEFT JOIN keeps every row from the left table, filling right-side columns with NULL when there is no match.'},
{lang:'SQL',diff:'Advanced',topic:'Views',question:'What is a SQL view?',code:'',options:['A) A physical copy of data','B) A stored, named query that acts like a virtual table','C) An index type','D) A user account'],correct:'B',explanation:'A view is a saved query you can select from like a table; it stores the definition, not the data itself.'},
{lang:'SQL',diff:'Advanced',topic:'Aggregations',question:'Why might COUNT(column) differ from COUNT(*)?',code:'',options:['A) They are always equal','B) COUNT(column) ignores NULLs','C) COUNT(*) ignores NULLs','D) COUNT(column) counts duplicates only'],correct:'B',explanation:'COUNT(*) counts all rows, while COUNT(column) skips rows where that column is NULL.'}

];
